<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>demo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ef681250-9d6a-4192-b891-4c7d5f9d75f8</testSuiteGuid>
   <testCaseLink>
      <guid>3faa733b-04aa-409b-a812-e10a02e25a3d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/botCreation_Test</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3e16e2ca-7421-4054-ad31-6fe4568443fc</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/dryRun</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>3e16e2ca-7421-4054-ad31-6fe4568443fc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>botName</value>
         <variableId>8cbed633-6148-4005-b19d-c81f4e6aa81f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a8b034c0-a964-48b2-9bbc-e4ba7b4f67af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/botSideOptionsNavigation_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>92b03ba9-9ef3-46c4-8dfd-f26c2da1f87e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/botUrlAndDefaultArticleConfiguration_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa994c75-1bc1-4f3a-a12d-4eeee22b537a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80bfff37-b144-4dfb-aeba-a3b989ae88af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f24a21be-9150-46d5-a957-67e3d6f58cab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dab31603-8956-4ab5-90d5-a91fdb8221a9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2bddf69e-c06a-4920-a731-65da90bc12ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/botCardMenuWithFallbackMessage_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1dd5505-bd5f-4a32-b998-1bd3b28d8bc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0305f5d-5ece-4741-8757-faf253a5bd1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a189ead-2095-47c0-a0d1-51bc827dcc4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35d67a2b-ab8f-4ae4-a32c-2f8b1bbc79e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aee8a6e9-561c-43a7-980e-5cc82a6e1e91</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4b00b0ab-6074-4aaf-bfd3-cbcc27f8ac74</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/importArticlesFromCsv_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b7a0d83-cf72-4548-bee8-74684c00f39b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaeb031f-8082-4ec2-83c5-a271a709015a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61866d72-ec9a-436e-ae42-9f887d127f7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6170963-e547-4825-9e94-b3791f646750</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b37ca8a5-212f-4dad-b691-bedb1a709ca0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/extractArticleFromExternalLink_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23137af1-a587-4766-af22-6dd4a37d7613</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>080576d5-3cab-4bf5-bbea-9f6eed5c903b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57dd9441-2fc8-4df7-ba8b-50292f222c7a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a73fb3fc-38db-448c-8a49-9384ff0c033e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/searchArticle_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae6412db-7dcc-4c03-bb63-746df0bb27d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85c0fa73-e392-4df7-bd42-6a8aadc3d9d0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f460c112-87bc-4e96-9e60-d2c50f5b3116</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/downvoteWithComment_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38221743-3644-48fb-8052-62d48fc14eaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7773d280-7493-4860-8df8-baed8e138e6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b6ef952-b80f-4d75-976a-603c3e2b3982</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc7e284d-2596-4708-9e36-54a38b7376fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a08d8708-37ed-4e1f-ac09-893a24575676</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2da026c3-f729-41fe-aefe-a7716b8c914d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fd08b15-3da9-4b3a-a453-3b6a981640b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6f91eba-6b40-4dd8-9f38-7e6b48118f62</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d5185e19-428f-44a2-a477-810a2a021911</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/addToCurationFromSessions_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d08ac8b1-3809-4b78-bb03-082b3170c279</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd024525-913f-4bde-840b-5c218c9106fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9b9243d-485a-47a5-9c45-7651f12469a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3b066d8-8872-43b4-82ac-56865435de97</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>143e2c60-758d-4c2c-9abc-37bce6d55549</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1245c9a5-4297-47b9-93e7-e5d94c45e709</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/createArticleWithRichResponseInCategory_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea77cce4-2be9-4298-b4b6-23ef34cddfb8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e59dd62-f050-4e65-8fc0-4a66c067b67a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bd67cd4-51ba-4699-92b9-e9f7f93cf6a4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>43181f9d-ace2-47b5-91a7-c390bf925d69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/modifyCategory_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67fbcebf-5525-4025-bf72-80175feee954</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0049aa1a-bc0b-4bbd-9c0e-4c6ce3a891b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/fallbackCurationByAddToExistingArticle_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72918d71-5ad3-4726-8570-eb1445cc4877</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02ed9b0b-ced3-49cc-b803-5dbce16d8164</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c03c3b8-c136-4678-a254-c5a8b560d554</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fe60e0f-5688-4c4c-9549-1a6687d0e063</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9eab2e19-89a4-42f3-97ba-0ac3b94719cc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e90da80-34e3-4915-84bf-ffe3750d83d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/partialMatchCurationByCreateNewArticle_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05be56a1-0932-4699-b645-91af123d8beb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee4147a3-efee-41ea-a256-a17c036f7f36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a92c8fbf-40f8-4f7d-b74c-95e4b22cbfa0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>746a7aff-1375-4da9-9f72-1d568b1107b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f535f48d-cae0-4303-af9b-643c9c2edcc7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02f796a9-ed55-4cad-ab5c-8b6fd0318317</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>473bcda0-1d05-4652-b262-949f26266efa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/filterSessionsBy_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbc3be87-e0ea-43a1-8bf4-180d7a77d05c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f7a0ecf-cd0b-4081-8efb-1c0a98fa5ce2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
