<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>EntityMarkingTagging</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>5ebc1f6c-e731-4635-a108-fc43d42c77a0</testSuiteGuid>
   <testCaseLink>
      <guid>9ed00100-c449-490f-8018-2fefee1aafe1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OldScripts/1_EntityRegression/verify_entity_auto_detection</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7512d130-d3f9-427d-8484-7f0c0acf60fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04190ead-dc55-4046-8d56-81c3cb018475</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2d757de0-9279-4ee3-8a70-7b95dacdf139</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OldScripts/1_EntityRegression/verify_manually_removal_of_entity</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc24d2ed-aa5a-48b4-bb7a-f624f73a67d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>82808352-5198-4ed3-a66c-d7e7fea4fd6b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OldScripts/1_EntityRegression/verify_multiple_entity_auto_detection</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3714574c-8290-46a0-89ac-ed00af82bfe6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a70b546-6e24-4d55-a8fa-87e29ab83250</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54bfcca8-7444-44f9-8889-cdd35daba31c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bce46c24-ee09-453f-b1ce-9542ce8de161</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OldScripts/1_EntityRegression/verify_value_markup_on_entity_deletion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a2d9c09-cab6-43bd-a3a7-2cb78e9eaf82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab03dd7c-9415-45a4-8b67-af399c05768e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c4a884f-ef15-4b80-91ef-31007417e174</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OldScripts/1_EntityRegression/verify_entity_markup_follows</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2c54332-8a71-4b27-9411-793c9ea8aade</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc76cc8f-94ae-4ad3-8aff-dc240d364adb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2082c984-d1d6-4b8d-86c0-4fc47bd2c786</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>50df76bc-e082-4257-9252-696d28de2325</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OldScripts/1_EntityRegression/verify_entity_tagging_and_removing_manually</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fae7441-480c-4da2-b56b-559aad592035</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>177a400b-d16a-432c-8abb-a6ee16ee68f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>51f1cbe0-3596-4f9d-bf1b-d2b69bebd1f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OldScripts/1_EntityRegression/verify_entity_creation_from_utterance</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbefd590-7fac-4a43-8778-33d742f7816f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32e25096-ccba-4758-92db-1bd8f573e80d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>378a9df8-89d4-4158-921b-f817ef7ee6e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2693fa9c-ad54-43f2-9f37-f407ef2f53fb</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
