<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>faqSuiteE2E</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>cddee02b-9fde-49ad-836a-e29aa9af5739</testSuiteGuid>
   <testCaseLink>
      <guid>5efd5d60-2534-43b6-81d5-b54115b7d322</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/botCreation_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cbed633-6148-4005-b19d-c81f4e6aa81f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2ea79ec7-13ee-4752-9cc5-c76b9318550d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/botSideOptionsNavigation_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8c78862c-38d2-49f5-80d9-a474a12da598</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/botUrlAndDefaultArticleConfiguration_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa994c75-1bc1-4f3a-a12d-4eeee22b537a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80bfff37-b144-4dfb-aeba-a3b989ae88af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f24a21be-9150-46d5-a957-67e3d6f58cab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dab31603-8956-4ab5-90d5-a91fdb8221a9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b07b35cd-cf02-4121-bb96-49a44e885231</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/botCardMenuWithFallbackMessage_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1dd5505-bd5f-4a32-b998-1bd3b28d8bc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0305f5d-5ece-4741-8757-faf253a5bd1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a189ead-2095-47c0-a0d1-51bc827dcc4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35d67a2b-ab8f-4ae4-a32c-2f8b1bbc79e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aee8a6e9-561c-43a7-980e-5cc82a6e1e91</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1818cfb9-cffa-486d-857d-26e136940e8d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/importArticlesFromCsv_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b7a0d83-cf72-4548-bee8-74684c00f39b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaeb031f-8082-4ec2-83c5-a271a709015a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61866d72-ec9a-436e-ae42-9f887d127f7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6170963-e547-4825-9e94-b3791f646750</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>960817cf-ac61-4f97-b3c6-e73983bea575</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/extractArticleFromExternalLink_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23137af1-a587-4766-af22-6dd4a37d7613</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>080576d5-3cab-4bf5-bbea-9f6eed5c903b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57dd9441-2fc8-4df7-ba8b-50292f222c7a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2c19fd6-9a6b-48c8-9c9a-792c28fd5877</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/searchArticle_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae6412db-7dcc-4c03-bb63-746df0bb27d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85c0fa73-e392-4df7-bd42-6a8aadc3d9d0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>525daacf-98e3-4b3f-b70b-8c9e6129a784</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/downvoteWithComment_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38221743-3644-48fb-8052-62d48fc14eaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7773d280-7493-4860-8df8-baed8e138e6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b6ef952-b80f-4d75-976a-603c3e2b3982</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc7e284d-2596-4708-9e36-54a38b7376fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a08d8708-37ed-4e1f-ac09-893a24575676</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2da026c3-f729-41fe-aefe-a7716b8c914d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fd08b15-3da9-4b3a-a453-3b6a981640b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6f91eba-6b40-4dd8-9f38-7e6b48118f62</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>016a6ba4-6b52-44f0-b624-faf859673c9d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/addToCurationFromSessions_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d08ac8b1-3809-4b78-bb03-082b3170c279</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd024525-913f-4bde-840b-5c218c9106fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9b9243d-485a-47a5-9c45-7651f12469a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3b066d8-8872-43b4-82ac-56865435de97</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>143e2c60-758d-4c2c-9abc-37bce6d55549</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0250e3a7-6bcb-4912-a8f9-63e36ee530c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/createArticleWithRichResponseInCategory_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea77cce4-2be9-4298-b4b6-23ef34cddfb8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e59dd62-f050-4e65-8fc0-4a66c067b67a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bd67cd4-51ba-4699-92b9-e9f7f93cf6a4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f860725f-123a-4cdf-b5cc-adc316e8870a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/modifyCategory_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67fbcebf-5525-4025-bf72-80175feee954</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>40a70dfc-1d88-4991-97f2-898cae266ef0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/fallbackCurationByAddToExistingArticle_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72918d71-5ad3-4726-8570-eb1445cc4877</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02ed9b0b-ced3-49cc-b803-5dbce16d8164</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c03c3b8-c136-4678-a254-c5a8b560d554</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fe60e0f-5688-4c4c-9549-1a6687d0e063</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9eab2e19-89a4-42f3-97ba-0ac3b94719cc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb42181d-33d5-46bc-b914-766a07ba3e0e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/partialMatchCurationByCreateNewArticle_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05be56a1-0932-4699-b645-91af123d8beb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee4147a3-efee-41ea-a256-a17c036f7f36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a92c8fbf-40f8-4f7d-b74c-95e4b22cbfa0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>746a7aff-1375-4da9-9f72-1d568b1107b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f535f48d-cae0-4303-af9b-643c9c2edcc7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02f796a9-ed55-4cad-ab5c-8b6fd0318317</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>39303475-4faf-4167-8890-42e778a5d788</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/filterSessionsBy_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbc3be87-e0ea-43a1-8bf4-180d7a77d05c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f7a0ecf-cd0b-4081-8efb-1c0a98fa5ce2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3506653c-b5a2-4d41-abd1-400d04235f54</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/oneClickTestingTrainedVersion_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec41ffe1-5830-4707-9b7a-2f51fc18499e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d297b461-2be1-4663-af10-24786842d292</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75ead96e-768a-4e99-b003-fa164589051d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7c66d828-eefe-4916-a00f-054bf2202d8f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/agentHandoverE2E_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5eddc80c-e0a9-4dce-abcb-cbf2399b213b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f323ddbe-c512-46b3-910d-25d64697d83c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>028bf5a8-9f66-464c-bd27-f2d194793092</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73ef163b-1e1c-4b9c-95e9-de7a85bf1eee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1fdb620-0670-48dd-9372-6b9d47df7ba1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6575b467-24df-4a55-8fb6-4c29a66927a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88e3aac3-ff93-4d69-bf06-f0e2a28bc590</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/disabledLowConfidenceAndDownvote_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c65e001-c756-468d-9e2a-f6205b3a6949</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea707175-8032-4991-9e0f-bcdd27751dd2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>238f744f-1974-46dc-b933-1839755a29f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/disabledPartialMatch_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c0be840-90b7-4faf-ad0e-6dae3e208ef0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c843b654-c1d3-4806-b662-0268782caee0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5554d55-2039-4f5f-8098-83c16a723055</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2c17eceb-4486-43cd-9deb-c5b0b979f3bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/disabledFallback_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbcac492-37af-4804-b078-d2df8b9377dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8672782b-691e-4353-9456-a796c7f4b455</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4be18b2d-4910-4818-88f9-b0bfa477c8a0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e1427867-640a-44b2-a2d4-32fd47428133</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/defaultQuestionInArticle_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ed1199a-3209-4ae2-b2e8-64735ec7429e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7c9641b-c310-4ee7-94d8-6484669fb3b5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6f3459b7-6b8f-4b3e-ba64-4f8e20e68f14</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/encryptionOnSessions_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b13eb69-b5d0-4905-ba8b-c6a369b0b4fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>33b33163-fd60-4d41-8691-bbf37ec312aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SetUp/setUpCustomSyn_ShareablePreview3</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>66e78b2f-0fa0-48b8-ab18-6d38aecc6ca6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/customSynonymsE2E_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e1457e9-1bb6-4e57-b1a9-84a441976721</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
