<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>generic</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>8ca86d8a-b4e4-4e10-b575-6fcf42e2972c</testSuiteGuid>
   <testCaseLink>
      <guid>c1bab596-184a-4d3c-a0d3-33cba9c751be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Generic/forgotPasswordLink_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>2165963e-904e-4eac-998c-3a6cb499253b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/botPageAndHeaderAccess_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>818321eb-011d-4535-b18c-c6a6c392cc6d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Generic/adminUserDetailsAndEnterpriseOption_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a413d1d-c8c8-4197-9efe-516ccb205cdd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b210965-79cc-4722-98f1-907ebcfe91cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/adminServiceKeyFunctionality_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>fbf3933c-4727-4b07-b924-7457ac3accb7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/adminUserManagement_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c2eb3a7-2dc2-473d-9b03-fea38434c6e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff585d13-7575-494d-b81b-48b3251964af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79bc24e0-69f5-4a24-aa42-3f88d80a489a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7db4ba75-eb69-481c-9d31-abf355ee36a9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Generic/adminUserDeletion_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cffc5bb3-67f6-4da1-b548-22d3407dccdf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f6b37f9-8b40-49a0-aee0-86154f888245</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>28c0207c-f7b7-481c-8c5a-b4ff1fc4e968</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/adminRoleManagement_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea01aa74-b0a0-4d77-b46b-70e0281e5ea5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>354ffabd-4c38-4e6e-94db-924f1d9df2f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>261f6865-1f5a-40fe-a2f2-20e709a8eb0d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>717ed42e-5f1f-42c1-b671-f3d890328d62</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/adminRoleDeletion_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6edb4c70-c7dc-491d-8b2f-9b1914b65e79</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Sprint/v4.3/autoAddNewBots_Test</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
