<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Regression</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>08e6f2fd-c4dd-4ba7-a770-d90e8351feeb</testSuiteGuid>
   <testCaseLink>
      <guid>aee92b5a-a1a3-487a-beb1-cc037de7e300</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Generic/loginPage_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88692dc3-c18c-403f-bb0b-78be204d20ab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>06600d0c-49a5-45d9-86cb-15e981699f01</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Generic/successfulLogin_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d8a4855-cd84-44fe-b5d4-92e02ef10b7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82f98cb3-0910-4e01-acdf-9b0af6095d1b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6f9440fa-8176-4a76-aed6-61b53eb5c687</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/botCreation_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cbed633-6148-4005-b19d-c81f4e6aa81f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7561e6da-7ec8-4a0f-a22b-bea2a8e8a5e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Faqbot/botSideOptionsNavigation_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bc612e8a-27b3-4cc0-a22a-d8a186e108ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/botUrlAndDefaultArticleConfiguration_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa994c75-1bc1-4f3a-a12d-4eeee22b537a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80bfff37-b144-4dfb-aeba-a3b989ae88af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f24a21be-9150-46d5-a957-67e3d6f58cab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dab31603-8956-4ab5-90d5-a91fdb8221a9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>00f92771-d5a1-43bf-a301-b8d2bb75418b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OldScripts/FAQ_updatePartialMatch_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6f91eba-6b40-4dd8-9f38-7e6b48118f62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2ce9322-be1e-4433-bc09-4c89a2f47784</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b51b8205-50a1-43e0-9295-1045aa504dc6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/botCardMenuWithFallbackMessage_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1dd5505-bd5f-4a32-b998-1bd3b28d8bc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0305f5d-5ece-4741-8757-faf253a5bd1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a189ead-2095-47c0-a0d1-51bc827dcc4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35d67a2b-ab8f-4ae4-a32c-2f8b1bbc79e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aee8a6e9-561c-43a7-980e-5cc82a6e1e91</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a4d25daf-2d87-47f5-b574-6c0bc3f7a7dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/importArticlesFromCsv_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b7a0d83-cf72-4548-bee8-74684c00f39b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaeb031f-8082-4ec2-83c5-a271a709015a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61866d72-ec9a-436e-ae42-9f887d127f7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6170963-e547-4825-9e94-b3791f646750</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a625ca3b-f27c-47f8-b77b-2dfcf1b9efde</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/extractArticleFromExternalLink_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23137af1-a587-4766-af22-6dd4a37d7613</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>080576d5-3cab-4bf5-bbea-9f6eed5c903b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57dd9441-2fc8-4df7-ba8b-50292f222c7a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>861c6032-a279-4638-b9fc-7a9195604aec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/searchArticle_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae6412db-7dcc-4c03-bb63-746df0bb27d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85c0fa73-e392-4df7-bd42-6a8aadc3d9d0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>90b40b9b-de53-46f7-bfb5-6fc0c65e952c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/downvoteWithComment_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38221743-3644-48fb-8052-62d48fc14eaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7773d280-7493-4860-8df8-baed8e138e6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc7e284d-2596-4708-9e36-54a38b7376fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a08d8708-37ed-4e1f-ac09-893a24575676</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2da026c3-f729-41fe-aefe-a7716b8c914d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fd08b15-3da9-4b3a-a453-3b6a981640b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6f91eba-6b40-4dd8-9f38-7e6b48118f62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b6ef952-b80f-4d75-976a-603c3e2b3982</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f21523f4-6c23-477a-8ba3-8ba2b88821b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/addToCurationFromSessions_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd024525-913f-4bde-840b-5c218c9106fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9b9243d-485a-47a5-9c45-7651f12469a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3b066d8-8872-43b4-82ac-56865435de97</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>143e2c60-758d-4c2c-9abc-37bce6d55549</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d08ac8b1-3809-4b78-bb03-082b3170c279</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>182fa70f-72f3-4a14-98e1-6383d66d65b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/createArticleWithRichResponseInCategory_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea77cce4-2be9-4298-b4b6-23ef34cddfb8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e59dd62-f050-4e65-8fc0-4a66c067b67a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bd67cd4-51ba-4699-92b9-e9f7f93cf6a4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4e70b1d-a085-4b31-acfa-895cc94e85ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/modifyCategory_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67fbcebf-5525-4025-bf72-80175feee954</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>171e344e-fd56-4551-833b-e4daabbd0ae2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/fallbackCurationByAddToExistingArticle_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72918d71-5ad3-4726-8570-eb1445cc4877</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02ed9b0b-ced3-49cc-b803-5dbce16d8164</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c03c3b8-c136-4678-a254-c5a8b560d554</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fe60e0f-5688-4c4c-9549-1a6687d0e063</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9eab2e19-89a4-42f3-97ba-0ac3b94719cc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0f1bb0e0-61a7-44c6-8148-ad343058c6f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/partialMatchCurationByCreateNewArticle_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05be56a1-0932-4699-b645-91af123d8beb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee4147a3-efee-41ea-a256-a17c036f7f36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a92c8fbf-40f8-4f7d-b74c-95e4b22cbfa0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>746a7aff-1375-4da9-9f72-1d568b1107b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f535f48d-cae0-4303-af9b-643c9c2edcc7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02f796a9-ed55-4cad-ab5c-8b6fd0318317</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b80545f-f531-4bb6-97fd-321ed5705592</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/filterSessionsBy_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbc3be87-e0ea-43a1-8bf4-180d7a77d05c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f7a0ecf-cd0b-4081-8efb-1c0a98fa5ce2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>79a40eb6-9233-4686-a202-48bf77069843</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/oneClickTestingTrainedVersion_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec41ffe1-5830-4707-9b7a-2f51fc18499e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d297b461-2be1-4663-af10-24786842d292</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75ead96e-768a-4e99-b003-fa164589051d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7a25f28-622d-44f2-bff4-d674fa342659</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/agentHandoverE2E_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5eddc80c-e0a9-4dce-abcb-cbf2399b213b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f323ddbe-c512-46b3-910d-25d64697d83c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>028bf5a8-9f66-464c-bd27-f2d194793092</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73ef163b-1e1c-4b9c-95e9-de7a85bf1eee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1fdb620-0670-48dd-9372-6b9d47df7ba1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6575b467-24df-4a55-8fb6-4c29a66927a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9c813a40-8456-46fe-abed-5fc79b3a5ace</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/disabledLowConfidenceAndDownvote_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c65e001-c756-468d-9e2a-f6205b3a6949</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea707175-8032-4991-9e0f-bcdd27751dd2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>28956d3a-6148-4e0d-a987-e3fe69329010</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/disabledPartialMatch_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c0be840-90b7-4faf-ad0e-6dae3e208ef0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c843b654-c1d3-4806-b662-0268782caee0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5554d55-2039-4f5f-8098-83c16a723055</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c55a3c28-1886-4e25-9cfe-48bc4b43ef70</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/disabledFallback_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbcac492-37af-4804-b078-d2df8b9377dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8672782b-691e-4353-9456-a796c7f4b455</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4be18b2d-4910-4818-88f9-b0bfa477c8a0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>033b63cd-1a69-42c7-8f27-b8f5a3c5a38b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/defaultQuestionInArticle_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ed1199a-3209-4ae2-b2e8-64735ec7429e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7c9641b-c310-4ee7-94d8-6484669fb3b5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dba6fca1-ea62-4e44-9f7e-b2929cd2335e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/customSynonymsE2E_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e1457e9-1bb6-4e57-b1a9-84a441976721</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>29d8e9b9-8cab-4427-9fa8-676547cec586</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Faqbot/encryptionOnSessions_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b13eb69-b5d0-4905-ba8b-c6a369b0b4fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7b6dc4b0-d9f6-4c25-a2b8-ab53c1d3504f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Smartbot/botCreation_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bab234a2-715e-4f3e-8ce8-66a72b3b3c1f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c19edfe3-4b55-42b7-a873-ae799b34631c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Smartbot/nlpConceptCreation_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e3c1c4f-3f40-4602-be8c-158fab51dd92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b7d1520-d961-4561-a015-b233de23ee6b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>652792e4-bb13-40d1-b0e5-d0d2c05867f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Smartbot/setUpLogicAndBotPreviewTest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cee9040f-ec4b-441a-9bba-2d7dab02d801</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>514b1396-c9f2-44fe-bd45-e85ca549bc96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2450f3cf-0eb6-4e7c-b6dd-3e282d199743</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a4af2782-fd09-4acc-bdac-be295cdf830e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Smartbot/maskingConcept_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1d6f3899-3c71-4c11-ae5e-fb696e7baa1f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Smartbot/oneClickTestingDisabledCallback_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebda178a-e15e-48ec-940e-8a49009f599d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19c6c272-fff1-46bb-b9dd-d71926941b3f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>70bd81ad-df99-42e6-8f4a-871a847198c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Smartbot/roomCloseCallback_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4aa0e28-5e1a-4f89-8d96-1f4631523f47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4550ceb8-6336-42d3-aade-9002809579f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3496775a-a4b4-4adf-a357-766cdaafc849</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ee801d6d-2e2e-47b9-a201-0b9f02e1b4fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/botCreation_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33365a28-4e39-4bf9-ba4a-3f42a41d6334</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4aedf4e0-cc8a-4b36-aa59-aac0637d559d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/botCardMenu_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>2942af6d-131f-4e2d-993c-64b05d8b5f25</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Taskbot/sideNavigation_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>fcc1bdc9-4be4-4a6d-8b19-50a2c5e2a70b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/createRichDynamicResponse_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0bf6b34b-2a46-4646-94c4-e3da1b870a6a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/entitiesCreationAndUpdate_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b1ad1b7-4109-4ac4-b63c-b1a3da33ffba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95c62713-639b-4763-986e-0dd3ad3298a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10d417dd-ddb8-4ef1-bd2c-ab864850a9cf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2e1f10cd-b6b9-4791-9bd2-6c9ff9a0c9f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/createIntentAndEditEntity_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ee6d9186-498f-462f-9a6e-3669e13b7fbe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/intentWithResponseCreation_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ff8ceb5-a18e-4913-9111-4e31c1d9a867</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7f41d91a-91d1-43b8-a498-6a6d4e07600f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/updateResponse_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>57e7f95c-ee14-4ec0-800e-2042d3c32132</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/downvoteWithComment_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9aba51fa-7a77-4cab-b094-25cbbebc4593</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f7e508b-c118-42a9-a158-2500af6aff08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e849def-ad0a-4117-8cae-f6005a11e575</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>141718ca-8e34-42f5-8606-142471d838bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/createNewIntentCuration_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc14672d-867b-45c2-93a1-b0af88a89ee4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ddf7598d-b53a-4cd7-9c17-df2b595e7cfc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/oneClickTestingNoCallback_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d8929a1-7243-42a9-bbca-7c2e61018b99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cb3bdb8-636b-4d79-808d-2d46ad9f0ded</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>65cc9970-0edf-4f20-bc01-dcfd867ce61d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Taskbot/configureCallback_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58477847-270e-4146-92b5-aa14542f261c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db691ed2-fa54-4c80-b7bb-ceb47ea4aca6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5c883b4f-e1a7-41ad-954b-1c3ca68828bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/agentHandover_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42f0f1a9-d681-469f-bad6-aa7be1ee2b73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bc92fa1-c840-4521-9bbb-0dee40a9a6df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>918e8441-1e85-4753-b41b-f553405dd418</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>791cc0c4-d3f3-4b8b-b551-10a0488ae872</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/explictAgentHandover_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6195d79b-0400-4ca2-867e-f4d143d16f44</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b89dca52-2333-434e-abc1-ab3e082c52f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/partialMatchResponseConfiguration_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28e305d0-6d80-4d75-8106-47ad3dfce22b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>94ca15b6-0ffa-4209-88bc-3ab302e1914d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Taskbot/oneClickTestingWithCallback_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4dda2c8e-e939-4ed1-95cd-af5ed13b48bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12cb5788-210d-400c-a214-0985c4f30680</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fc5e2818-04bd-4cf2-a6f0-c17463773b1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/encryptionOnCurationAndSessions_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>935c9988-c92d-405e-a4e1-14a245b35001</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/noneIntentE2E_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95d73e81-5717-4c21-9253-9efadd341007</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa67a951-a8a0-41e8-8279-2e8d2a6632f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b04d81b5-0cdd-4f8f-9b7f-845b0ded80af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/globalSearchOnTraining_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a844087-db4b-4391-b73f-804b9807ecb1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5587d6ac-529e-40e3-a618-341eb8abe60f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Routerbot/botCreation_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94edb99a-a6e8-45f6-abf2-94f728cc14a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d65df64-b467-4f0a-8dd9-28200bb6e4e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef21d189-c564-4f29-811d-22c286af0268</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>81993a78-f21d-4c81-b795-cada22f59a33</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Routerbot/sideOptionsNavigation_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f3d9b662-19d3-4344-94a4-5ffcd0c7015c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Routerbot/nlpConceptCreation_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e3c1c4f-3f40-4602-be8c-158fab51dd92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b7d1520-d961-4561-a015-b233de23ee6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afa580fc-d2a9-4c6a-af39-653393f31931</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>545505b6-2e1f-42cf-a14b-8611b2e6e902</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a7e4874f-c5fc-4d34-9690-9c245074885d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Routerbot/ruleConfiguration_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6bc3d981-c255-4663-8ff0-6a5faeb5bc01</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Routerbot/ruleAddition_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98fe4e25-24bb-4777-b446-f7f0bebd0f0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f9393e3-eaa2-4d24-92c0-366720178d69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0890159d-0c3b-4b15-a417-e435d237923e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5529e38e-bc20-4d06-b290-e0c760265cf3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aef1bbda-24e2-4352-b564-ec5ce432a85d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0660347c-c500-4bf6-9f3a-a1d1d1e0e344</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b2d9971-0348-4af4-9e0e-8861dfdcdc24</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ce0b824-5a29-4e82-b313-faadbe75090e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pipelinebot/verify_pipeline_bot_creation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94e58f0a-de19-41c8-a615-c599e0eb191d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a61b748b-d1f5-4525-89d4-dffe324c7dd1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/forgotPasswordLink_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>be1b42f8-7476-4f1e-839c-3958acc75394</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/botPageAndHeaderAccess_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f85f39e6-2c13-45c4-8178-cd51561a9999</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Generic/bots_Dashboard_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9649e3c4-a29c-48bc-9bc1-99a379b742af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Generic/admin_enterpriseOptions_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cad5ddc-6aee-4afc-9b88-d330d00d2abe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eedb0266-686b-4969-ac8f-05f28aed7442</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/adminUserDetailsAndEnterpriseOption_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a413d1d-c8c8-4197-9efe-516ccb205cdd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a8ce243c-97bd-4bbc-ba19-31ae94cdeed3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/adminServiceKeyFunctionality_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b09eabc5-f33e-4801-a4de-0ee2a0529e1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/adminUserManagement_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c2eb3a7-2dc2-473d-9b03-fea38434c6e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff585d13-7575-494d-b81b-48b3251964af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79bc24e0-69f5-4a24-aa42-3f88d80a489a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>02bf906c-2672-4c7b-b68d-10e52d769320</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Generic/adminUserDeletion_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cffc5bb3-67f6-4da1-b548-22d3407dccdf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f6b37f9-8b40-49a0-aee0-86154f888245</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac7689bf-a489-465b-b183-593a2c7b2a15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/adminRoleManagement_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea01aa74-b0a0-4d77-b46b-70e0281e5ea5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>354ffabd-4c38-4e6e-94db-924f1d9df2f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>261f6865-1f5a-40fe-a2f2-20e709a8eb0d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f248c874-5383-4b15-8386-ca7c4ee4a4f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/adminRoleDeletion_Test</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
