<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>routerSuiteE2E</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>6421c5d7-26f4-4670-ba5d-0ed6a5b26713</testSuiteGuid>
   <testCaseLink>
      <guid>ca015299-fc14-498a-a07e-1a351d003719</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Routerbot/botCreation_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94edb99a-a6e8-45f6-abf2-94f728cc14a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d65df64-b467-4f0a-8dd9-28200bb6e4e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef21d189-c564-4f29-811d-22c286af0268</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f896810c-277b-4b9f-be18-ff13079c49f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Routerbot/sideOptionsNavigation_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7c86b7b0-05eb-4ffb-9beb-106f286ba2db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Routerbot/nlpConceptCreation_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e3c1c4f-3f40-4602-be8c-158fab51dd92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b7d1520-d961-4561-a015-b233de23ee6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afa580fc-d2a9-4c6a-af39-653393f31931</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>545505b6-2e1f-42cf-a14b-8611b2e6e902</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eb7947fc-bf90-4c1b-a7e0-dd0af1021e9d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Routerbot/ruleConfiguration_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4109cba2-3e98-4fb7-971a-c9fecd0ce81b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Routerbot/ruleAddition_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98fe4e25-24bb-4777-b446-f7f0bebd0f0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f9393e3-eaa2-4d24-92c0-366720178d69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0890159d-0c3b-4b15-a417-e435d237923e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5529e38e-bc20-4d06-b290-e0c760265cf3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aef1bbda-24e2-4352-b564-ec5ce432a85d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0660347c-c500-4bf6-9f3a-a1d1d1e0e344</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b2d9971-0348-4af4-9e0e-8861dfdcdc24</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb8761f6-7eeb-4ead-8e4e-bcf83cce7cb4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Routerbot/feedbackFunctionality_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a096e6e0-1394-4c0a-b950-cb3425c54b36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5948fd6-1bdb-408a-9ff7-be1ac31e315d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69bca680-b362-4978-b1ad-359454a1449e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>22898850-a53a-475a-978f-1538ec1805e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Routerbot/consumerIDVerificationInChildbots_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abc6ae56-6cf2-4280-9486-a6b7d27d7a2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df29d6b3-9e60-4a47-9325-ec8c3505662d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fc94e7fe-dbc5-4b2b-a20f-e0913bc4d450</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Routerbot/botDisabled_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>386bec97-5522-4f12-9148-8818472d8897</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pipelinebot/verify_pipeline_bot_creation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94e58f0a-de19-41c8-a615-c599e0eb191d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
