<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Sanity</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b950d831-c770-4e07-8fde-4ff663ca4d1e</testSuiteGuid>
   <testCaseLink>
      <guid>de6c6f1c-a5b4-473c-9d69-3590a6f4025a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/loginPage_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88692dc3-c18c-403f-bb0b-78be204d20ab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>953784c5-cfbb-4d01-923b-38abf0f4fec6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/successfulLogin_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d8a4855-cd84-44fe-b5d4-92e02ef10b7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82f98cb3-0910-4e01-acdf-9b0af6095d1b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9bd16420-6679-4234-a1e6-ea1e174dc643</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/botPageAndHeaderAccess_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>effa5d0a-8fb7-41b2-a3ec-6ac03e35bf8b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/adminUserDetailsAndEnterpriseOption_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a413d1d-c8c8-4197-9efe-516ccb205cdd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>641ca72c-a620-4c51-88f9-d57ccfebac37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Generic/admin_enterpriseOptions_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cad5ddc-6aee-4afc-9b88-d330d00d2abe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1141f9d7-28f6-4a82-aa74-cbcb17769d8a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Generic/bots_Dashboard_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e8c1a0fe-d7b9-4a9a-b65c-864310e19964</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Faqbot/botCreation_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cbed633-6148-4005-b19d-c81f4e6aa81f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>55e6afff-55d9-4415-9927-8a54613f4853</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Faqbot/defaultPlatformPreview</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c5aab86-c52f-4a44-b6d4-dac5be34b34b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02e0cbf2-1ba1-41f3-8f4e-09ff1fc6dc54</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3591f241-a3fb-45e1-8e51-a8574a5df962</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Taskbot/botCreation_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33365a28-4e39-4bf9-ba4a-3f42a41d6334</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a8a1d8e1-3555-4285-8aa9-0ac71d20742b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Taskbot/botCardPreview_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16f74a6c-3597-460e-bea5-bc47addf91f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b3ded6c-2a48-44c9-9c45-8803bfd52210</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b4058086-fb17-47be-989d-aab5f2da5a91</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Smartbot/botCreation_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bab234a2-715e-4f3e-8ce8-66a72b3b3c1f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2eb3a990-5c65-44f3-b231-547040c17af8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Smartbot/defaultPlatformPreview_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33967b6e-c3c5-46df-b317-0a88d8870d77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d46d9017-74e8-4b4e-974b-40c76e726d56</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>deea0f13-adeb-4d7b-a19f-73d1f2e196cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Routerbot/botCreation_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94edb99a-a6e8-45f6-abf2-94f728cc14a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d65df64-b467-4f0a-8dd9-28200bb6e4e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef21d189-c564-4f29-811d-22c286af0268</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>684c2e27-8eca-48bc-8745-e7f3e392dd68</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Pipelinebot/verify_pipeline_bot_creation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94e58f0a-de19-41c8-a615-c599e0eb191d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>55c98beb-5a34-4cc1-a88a-0720a97377f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Taskbot/1_EntityRegression/verify_entity_auto_detection</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7512d130-d3f9-427d-8484-7f0c0acf60fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04190ead-dc55-4046-8d56-81c3cb018475</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5db8ba4e-5951-46a2-90f9-a9e982ae6239</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Taskbot/1_EntityRegression/verify_manually_removal_of_entity</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc24d2ed-aa5a-48b4-bb7a-f624f73a67d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b0fa1118-cb4a-4092-a244-445d830766bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Taskbot/1_EntityRegression/verify_multiple_entity_auto_detection</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3714574c-8290-46a0-89ac-ed00af82bfe6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a70b546-6e24-4d55-a8fa-87e29ab83250</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54bfcca8-7444-44f9-8889-cdd35daba31c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>08ec4e7c-9093-491c-9aca-b117a9be71a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Taskbot/1_EntityRegression/verify_value_markup_on_entity_deletion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a2d9c09-cab6-43bd-a3a7-2cb78e9eaf82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab03dd7c-9415-45a4-8b67-af399c05768e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a3f4bf39-6485-4735-994f-81ef5db04000</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Taskbot/1_EntityRegression/verify_entity_markup_follows</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2c54332-8a71-4b27-9411-793c9ea8aade</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc76cc8f-94ae-4ad3-8aff-dc240d364adb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2082c984-d1d6-4b8d-86c0-4fc47bd2c786</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>11527280-df9c-4bbd-9d70-a2e50bd6f1e4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Taskbot/1_EntityRegression/verify_entity_tagging_and_removing_manually</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fae7441-480c-4da2-b56b-559aad592035</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>177a400b-d16a-432c-8abb-a6ee16ee68f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>afd0fcc6-b38b-468e-a896-6938ec068d9c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Taskbot/1_EntityRegression/verify_entity_creation_from_utterance</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbefd590-7fac-4a43-8778-33d742f7816f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32e25096-ccba-4758-92db-1bd8f573e80d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>378a9df8-89d4-4158-921b-f817ef7ee6e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2693fa9c-ad54-43f2-9f37-f407ef2f53fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>29d315ab-11a8-48e9-8a3e-31fe819125e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Routerbot/botDeletion_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>cf17828a-e14c-4c51-a7ce-717f74455def</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Faqbot/botDeletion_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>cc680ef4-2fd7-436d-944a-ea10b844d06a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Taskbot/botDeletion_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4b39762e-cc2e-4f00-a0cc-faa1983dcb97</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Smartbot/botDeletion_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7e871ebd-2746-42d9-9f72-8fdd4394f8e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Pipelinebot/verify_pipeline_bot_deletion</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
