<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SMART_SSO</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>82aceed3-4484-4470-a1b3-7d0876e726a1</testSuiteGuid>
   <testCaseLink>
      <guid>a7e6d676-94d2-43f3-b345-ba5cd4fcf914</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Smartbot/botCreation_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bab234a2-715e-4f3e-8ce8-66a72b3b3c1f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b20e99b-a44c-443d-9f8e-41c528a3dde1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Smartbot/nlpConceptCreation_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e3c1c4f-3f40-4602-be8c-158fab51dd92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b7d1520-d961-4561-a015-b233de23ee6b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e599a372-b167-4b6f-b9e1-33db8454415a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Smartbot/setUpLogicAndBotPreviewTest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cee9040f-ec4b-441a-9bba-2d7dab02d801</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>514b1396-c9f2-44fe-bd45-e85ca549bc96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2450f3cf-0eb6-4e7c-b6dd-3e282d199743</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>29498cbf-323a-4e5c-a282-6775ae0a86ba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Smartbot/maskingConcept_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>69492f3f-5019-480e-8931-cdf49a8f6601</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Smartbot/oneClickTestingDisabledCallback_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebda178a-e15e-48ec-940e-8a49009f599d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19c6c272-fff1-46bb-b9dd-d71926941b3f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5a9b36b3-6a4d-439d-9c59-7e10d684f526</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Smartbot/roomCloseCallback_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4aa0e28-5e1a-4f89-8d96-1f4631523f47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4550ceb8-6336-42d3-aade-9002809579f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3496775a-a4b4-4adf-a357-766cdaafc849</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6ef6ae27-1dd2-4884-9c33-1b7462d0754c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Sprint/v4.3/autoAddNewBots_Test</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
