<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TASK_SSO</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>5d0f4e5d-c520-417d-9b61-295cbf97beac</testSuiteGuid>
   <testCaseLink>
      <guid>ff512865-8cda-4f15-a556-b00bfdc606f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TASK_SSO/botCreation_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2564246-4522-46ad-92e1-01b8357fbb89</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1148d37e-8f3a-4b71-baf9-b4131eb557f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TASK_SSO/botCardPreview_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebaadfc4-75e3-41ec-b728-e8e5a3c6ff66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b468bb89-9baa-4194-8e5d-018e10fda856</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>76238919-6bf4-472e-9622-030e7f9e721f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TASK_SSO/botCardMenu_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>729b9fd5-83a9-4d0a-9b32-ba9f05a70316</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TASK_SSO/sideNavigation_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b7540d00-410f-46b4-a17c-bdd604f1ed3a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TASK_SSO/createRichDynamicResponse_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>2cddfd15-af68-4e2c-9ff9-6979b2ccabd7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TASK_SSO/entitiesCreationAndUpdate_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ef5c106-c5a8-4042-93b6-935a615866bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c020d8e-a3ae-4033-93a7-57df21db01e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db9abb06-1bbc-4743-9f7e-a90a5a558a47</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0aab7941-587a-4e73-bf67-337e4d2f915c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TASK_SSO/createIntentAndEditEntity_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7cc7706f-567b-4501-b01f-d7d9924361c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TASK_SSO/intentWithResponseCreation_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c41b9e2f-7161-4b0d-8b0c-c50500c20db4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>74b406ec-9d70-4a37-80ab-746efd055758</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TASK_SSO/updateResponse_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>dd2315fd-0436-4ca1-91e3-3ee538bbdd21</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TASK_SSO/downvoteWithComment_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f323587-3ae7-45b6-acd6-0a722c3c507a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e86acd4f-985d-4e5f-b435-db3a5a0bab88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>326982c4-742c-4bf0-969e-ae3a4f84dc95</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df73366a-563a-4be2-b459-83333bbd66c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TASK_SSO/createNewIntentCuration_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64f4e1b4-36b7-4933-bb75-fa24a44fa6eb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>76520f9e-2016-4e5f-b0a4-1b82a34a0c44</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TASK_SSO/newIntentCreation_WO_TemplateKeyCreationInCuration</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b7a23e2-765e-4c37-997d-aff1f876f385</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aec8f229-93c5-42f9-b305-f8ca3cf94656</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TASK_SSO/oneClickTestingNoCallback_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0000d9df-54f1-4315-acea-4d7b2a598166</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc7b4d75-79d2-4304-b781-e71ef9632f02</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1a713925-2cdc-4c75-8351-4e4bed655fef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Taskbot/configureCallback_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58477847-270e-4146-92b5-aa14542f261c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db691ed2-fa54-4c80-b7bb-ceb47ea4aca6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6778e0a2-e1f2-49d7-9d49-0a633c578d72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TASK_SSO/agentHandover_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>511b8205-0518-4076-b696-5606577b045f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e29c01d-bd68-437f-8b85-2b6e2ebe303c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c6e278f-7580-46b4-9b66-7e7d2657c808</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f6a858d9-2b27-4bbe-ae45-a71c86ad279d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TASK_SSO/explictAgentHandover_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37bc90ca-4fd4-4f2a-8242-4dd7fc5a764e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa76b480-13d3-4fe9-b81b-776188280085</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TASK_SSO/partialMatchResponseConfiguration_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7907d0b-707e-451e-83d5-a44296cc52b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8bd9690a-0c55-4b22-83c5-3ab9ad803a69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Taskbot/oneClickTestingWithCallback_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4dda2c8e-e939-4ed1-95cd-af5ed13b48bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12cb5788-210d-400c-a214-0985c4f30680</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>332d9e66-a21a-4e12-81e2-ddb1c8cd5b98</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TASK_SSO/encryptionOnCurationAndSessions_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b56f6921-b645-451f-b89e-726c1034080d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/TASK_SSO/noneIntentE2E_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b80e9ee-f41d-4fd9-8137-7c3f41e8f612</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca5b2f60-6c31-4f52-af1c-083ff7d1470d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bd5ec9a8-152e-4256-8772-073f3651d120</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Sprint/v4.3/alertTestOnResponseDesignerTemplateTask</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a542ce9f-7d70-4f6a-bf0c-16a6c7184b3b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75ada6b6-a439-4009-8f60-ead491fcd383</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52e7e15b-27a9-43b0-9506-1db18b447b0e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>90886a9c-0722-4477-bb56-d3fe59bb8752</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Sprint/v4.3/appleBusinessChatFieldTestForTaskbot</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d075715-91be-4c8e-b3d1-8d5b4348106a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>703a6d51-3c76-4a2d-b1d2-4e918553c53d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>be562452-7d2f-4631-9bbe-3c2d6702c9be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/TASK_SSO/globalSearchOnTraining_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bb7faf6-d9ed-4365-85e9-352c7f6a163a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
