<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>v4.x_TaskSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ddcc45a7-4443-460f-a2be-6b63efec3a42</testSuiteGuid>
   <testCaseLink>
      <guid>b7ae3105-ee58-43a3-8177-4373d776a56f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TASK_SSO/botCreation_Test</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3e34afa8-7613-48d9-8002-091f1bb11ead</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/testSuiteData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>3e34afa8-7613-48d9-8002-091f1bb11ead</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Taskbot_Name</value>
         <variableId>c2564246-4522-46ad-92e1-01b8357fbb89</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>64f79cad-eef0-46d6-99d8-5d8aad435e66</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint/v4.4/mapLocationEntityCreation_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4cb4c6f7-e361-400f-98fa-23292042b17c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint/v4.4/mapLocationEntityTaggingInIntent_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49e02ed9-ecdb-4b4a-a1a9-13ee4ab490e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a51ae539-8f67-43b5-9cb9-88134705e888</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint/v4.4/mapLocationLinkToSlots_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5925318e-cf5a-4b60-b063-fac0f2c03976</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6a7ac3c-5565-4298-8933-633fa7d7c340</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1493a285-aaa3-413b-a3df-fd5bd22d76bc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e762c52f-2e1e-43a4-84f9-6241f796034e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint/v4.4/freeformEntityCreation_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d764dbe0-89f0-4176-8a3a-67662387581f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint/v4.4/freeformEntityTaggingInIntent_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1bd6d4f-0068-482e-b5e6-0221cfb45732</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>13bf77b0-f4c3-4c5e-a9d0-015be84ccaad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint/v4.4/freeformLinkToSlots_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a08ac529-31cb-45ea-a66b-1904e324a55d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7193854-e285-475f-8450-02a545b2a6e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72ca71dc-41ab-4fe8-bb70-4b53827d9041</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba201b30-61b8-4aad-afaa-e2f178b02ed8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>96bd416f-118c-43a5-a7c0-e9c44b929952</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint/v4.4/verifyFreeformPreview</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>649802f2-1fdb-4e15-aecd-92b26e5f8cc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b9c5304-396d-40b9-a8fb-68d42f1eddb9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6285746-9b12-45f5-bb96-d7b1e858d122</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a986316-952b-4286-af6f-b18041d2b9b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e3ed67a-3385-4197-b046-6438d89dc969</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a153911e-7ae8-40f6-9663-410aecc6f49a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8d81d44f-3ab3-4507-b5cc-0d172811ac98</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint/v4.4/textWithAttachments_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f036fe25-13bc-48d5-959d-c9d9bc34fb20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d2ac11c-2408-4373-9d2c-1c1e165a8d6a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
