<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lock</name>
   <tag></tag>
   <elementGuidId>e63bbaed-5e35-4b6b-bc44-ce0f2dcb9427</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>mat-icon[name='lock']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>mat-icon[name='lock']</value>
   </webElementProperties>
</WebElementEntity>
