<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toastMsg</name>
   <tag></tag>
   <elementGuidId>98016111-2005-48f1-aced-9db45f953e06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//simple-snack-bar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//simple-snack-bar</value>
   </webElementProperties>
</WebElementEntity>
