<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>itemTitleHeader</name>
   <tag></tag>
   <elementGuidId>fe43d9d0-76ff-4fa5-8fd1-f38c4e9b54e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class='list-picker-title-heading'])[${index}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class='list-picker-title-heading'])[${index}]</value>
   </webElementProperties>
</WebElementEntity>
