<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>articleCheckbox</name>
   <tag></tag>
   <elementGuidId>403d491b-0e0c-43e2-bb7f-807cf5dff2ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@formcontrolname='selected']/following-sibling::span[starts-with(@class,'checkmark')])[${index}]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
