<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>faqImportBtn</name>
   <tag></tag>
   <elementGuidId>ff67e5aa-02ca-4146-a623-07e702494a4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button//span[contains(text(),'Import')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(text(),'Import')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button//span[contains(text(),'Import')]</value>
   </webElementProperties>
</WebElementEntity>
