<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kbHeader</name>
   <tag></tag>
   <elementGuidId>98e6b2ee-a59a-4541-9325-7b6978776b98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
