<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>testSummary</name>
   <tag></tag>
   <elementGuidId>26e6ba5b-cb05-4f5d-9469-61ee6756ab0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'${status}')]/div[starts-with(@class,'summery-status')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'${status}')]/div[starts-with(@class,'summery-status')]</value>
   </webElementProperties>
</WebElementEntity>
