<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>taskSuiteE2E</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c6ba0c93-7b8d-481f-b377-5436b022de8c</testSuiteGuid>
   <testCaseLink>
      <guid>ff512865-8cda-4f15-a556-b00bfdc606f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/botCreation_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33365a28-4e39-4bf9-ba4a-3f42a41d6334</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>76238919-6bf4-472e-9622-030e7f9e721f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/botCardMenu_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1148d37e-8f3a-4b71-baf9-b4131eb557f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/botCardPreview_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16f74a6c-3597-460e-bea5-bc47addf91f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b3ded6c-2a48-44c9-9c45-8803bfd52210</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>729b9fd5-83a9-4d0a-9b32-ba9f05a70316</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/sideNavigation_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b7540d00-410f-46b4-a17c-bdd604f1ed3a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/createRichDynamicResponse_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>2cddfd15-af68-4e2c-9ff9-6979b2ccabd7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/entitiesCreationAndUpdate_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b1ad1b7-4109-4ac4-b63c-b1a3da33ffba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95c62713-639b-4763-986e-0dd3ad3298a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10d417dd-ddb8-4ef1-bd2c-ab864850a9cf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0aab7941-587a-4e73-bf67-337e4d2f915c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/createIntentAndEditEntity_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7cc7706f-567b-4501-b01f-d7d9924361c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/intentWithResponseCreation_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ff8ceb5-a18e-4913-9111-4e31c1d9a867</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>74b406ec-9d70-4a37-80ab-746efd055758</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/updateResponse_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>dd2315fd-0436-4ca1-91e3-3ee538bbdd21</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/downvoteWithComment_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9aba51fa-7a77-4cab-b094-25cbbebc4593</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f7e508b-c118-42a9-a158-2500af6aff08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e849def-ad0a-4117-8cae-f6005a11e575</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df73366a-563a-4be2-b459-83333bbd66c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/createNewIntentCuration_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc14672d-867b-45c2-93a1-b0af88a89ee4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>76520f9e-2016-4e5f-b0a4-1b82a34a0c44</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/newIntentCreation_WO_TemplateKeyCreationInCuration</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d7171e0-f557-4ddf-a3c1-833542cfea91</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aec8f229-93c5-42f9-b305-f8ca3cf94656</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/oneClickTestingNoCallback_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d8929a1-7243-42a9-bbca-7c2e61018b99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cb3bdb8-636b-4d79-808d-2d46ad9f0ded</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1a713925-2cdc-4c75-8351-4e4bed655fef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Taskbot/configureCallback_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58477847-270e-4146-92b5-aa14542f261c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db691ed2-fa54-4c80-b7bb-ceb47ea4aca6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6778e0a2-e1f2-49d7-9d49-0a633c578d72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/agentHandover_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42f0f1a9-d681-469f-bad6-aa7be1ee2b73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bc92fa1-c840-4521-9bbb-0dee40a9a6df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>918e8441-1e85-4753-b41b-f553405dd418</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f6a858d9-2b27-4bbe-ae45-a71c86ad279d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/explictAgentHandover_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6195d79b-0400-4ca2-867e-f4d143d16f44</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa76b480-13d3-4fe9-b81b-776188280085</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/partialMatchResponseConfiguration_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28e305d0-6d80-4d75-8106-47ad3dfce22b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8bd9690a-0c55-4b22-83c5-3ab9ad803a69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Taskbot/oneClickTestingWithCallback_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4dda2c8e-e939-4ed1-95cd-af5ed13b48bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12cb5788-210d-400c-a214-0985c4f30680</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>332d9e66-a21a-4e12-81e2-ddb1c8cd5b98</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/encryptionOnCurationAndSessions_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b56f6921-b645-451f-b89e-726c1034080d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/noneIntentE2E_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95d73e81-5717-4c21-9253-9efadd341007</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa67a951-a8a0-41e8-8279-2e8d2a6632f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>be562452-7d2f-4631-9bbe-3c2d6702c9be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Taskbot/globalSearchOnTraining_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a844087-db4b-4391-b73f-804b9807ecb1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
