<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>consumerSearchFieldInput</name>
   <tag></tag>
   <elementGuidId>d8f6f1bb-53d5-4bc5-a6f1-26f855c10666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//mat-form-field//input[@placeholder='${value}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//mat-form-field//input[@placeholder='${value}']</value>
   </webElementProperties>
</WebElementEntity>
