<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>consumerActions</name>
   <tag></tag>
   <elementGuidId>a9dda9d6-6f41-4a1d-87a2-8ed4dfdfab8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>input[placeholder='Actions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>input[placeholder='Actions']</value>
   </webElementProperties>
</WebElementEntity>
