<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label</name>
   <tag></tag>
   <elementGuidId>c2e08dbc-ff2c-469e-bf15-6927adcff76c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>label>mat-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>label>mat-label</value>
   </webElementProperties>
</WebElementEntity>
