<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>makeLiveModal</name>
   <tag></tag>
   <elementGuidId>632a5747-5065-4008-a8da-1ab804ce0a2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[class='modal-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[class='modal-title']</value>
   </webElementProperties>
</WebElementEntity>
