<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox</name>
   <tag></tag>
   <elementGuidId>7bd7cb28-0d7f-4b5f-91a0-271ca33fc819</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[2]/tr[${rowValue}]/td[3]/mat-checkbox</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//tbody[2]/tr[${rowValue}]/td[3]/mat-checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody[2]/tr[${rowValue}]/td[3]/mat-checkbox</value>
   </webElementProperties>
</WebElementEntity>
