<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>listOfCategory</name>
   <tag></tag>
   <elementGuidId>1e4b5418-b5ed-4f28-9f05-8b92920e79e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//mat-form-field//input[@formcontrolname='name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//mat-form-field//input[@formcontrolname='name']</value>
   </webElementProperties>
</WebElementEntity>
