<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>downvoteComment</name>
   <tag></tag>
   <elementGuidId>7c188084-2fcd-4db4-a6d7-1ad9900a804f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[contains(@class,'downvote-comment-textarea')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@class='downvote-comment-textarea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[contains(@class,'downvote-comment-textarea')]</value>
   </webElementProperties>
</WebElementEntity>
