<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>expectedColumn</name>
   <tag></tag>
   <elementGuidId>81ef9ea3-fa68-4d37-a3c5-51ce26a83bac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//td[@class='htAutocomplete'])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//td[@class='htAutocomplete'])[${index}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//td[@class='htAutocomplete'])[${index}]</value>
   </webElementProperties>
</WebElementEntity>
