<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchQuestion</name>
   <tag></tag>
   <elementGuidId>695486b0-d741-410c-955a-55333c089a92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-faq-search-box[@class=&quot;searchForArticle&quot;]//input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
