<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textResponse</name>
   <tag></tag>
   <elementGuidId>0a25218b-3368-45c1-baea-551dd75e07bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[starts-with(@class,'classic-textarea')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[starts-with(@class,'classic-textarea')]</value>
   </webElementProperties>
</WebElementEntity>
