<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>train</name>
   <tag></tag>
   <elementGuidId>527aba1e-6221-4aba-bbb4-bf2da3ede7a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(text(),'Train')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[contains(text(),'Train')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[contains(text(),'Train')]</value>
   </webElementProperties>
</WebElementEntity>
