<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>imageRes</name>
   <tag></tag>
   <elementGuidId>d7834bbc-e608-47bd-8a2f-f06a543896ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[starts-with(@class,'msg-img')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[starts-with(@class,'msg-img')]</value>
   </webElementProperties>
</WebElementEntity>
