<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelName</name>
   <tag></tag>
   <elementGuidId>e23092ed-3d7b-4121-afcf-0e88cde90c93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label/span[text()='${labelName}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label/span[text()='${labelName}']</value>
   </webElementProperties>
</WebElementEntity>
