<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon</name>
   <tag></tag>
   <elementGuidId>7143df29-6ebd-4151-8616-8b9e3b17e33d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[class*='${class_value}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[class*='${class_value}']</value>
   </webElementProperties>
</WebElementEntity>
