<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>overlay</name>
   <tag></tag>
   <elementGuidId>9db1dc07-6fc0-40dd-9e8f-18d2c75eb5f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>div[class='popover']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>div[class='popover']</value>
   </webElementProperties>
</WebElementEntity>
