<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>templateHeader</name>
   <tag></tag>
   <elementGuidId>0a4e9c6c-0be8-44d7-9f9d-747f41ac8b50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//header/h1)[${index}]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
