<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>type</name>
   <tag></tag>
   <elementGuidId>ed97db45-6c9a-41ad-9d65-a17317b24dde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select</value>
   </webElementProperties>
</WebElementEntity>
