<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>childBotCheckbox</name>
   <tag></tag>
   <elementGuidId>07faaec6-9916-4dac-8031-e5e91b789c76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//mat-pseudo-checkbox)[${index}]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
