<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>videoResponse</name>
   <tag></tag>
   <elementGuidId>0b3ca542-6626-4a2e-97bf-77473ecbe2a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//video</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//video</value>
   </webElementProperties>
</WebElementEntity>
