<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>callback</name>
   <tag></tag>
   <elementGuidId>88392139-f9f3-4815-b11f-90fd3a68e154</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-ui-switch[@formcontrolname='room_close_callback']//label/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
