<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>override</name>
   <tag></tag>
   <elementGuidId>176823f3-93c3-413a-a82c-690b3aa1383c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//mat-slide-toggle[@name='override']//label/div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-slide-toggle[@name='override']//label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//mat-slide-toggle[@name='override']//label/div</value>
   </webElementProperties>
</WebElementEntity>
